### ISSUE TITLE
Meta issue - comparison of license model to SPDX 2.3 model

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#224]
I went through and compared the [SPDX 2.3 UML class diagram](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/model/SPDX-UML-Class-Diagram.jpg) to the SPDX 3 license model.

Below is a summary of the differences I found with references to separate issues to track decisions on if we should change from the 2.3 model.

- [x] Class `LicenseExpression` is named `AnyLicenseInfo` in 2.3.  Issue  #222 
- [x] Classes `CopyrightText`, `CopyrightTextField` are just string fields in 2.3.  Related to issue #76 
- [x] Class `CustomerLicense` is named `ExtractedLicenseText` in 2.3. Issue #223
- [x] Class `LicenseField` is not present in the 2.3 model.  Related to issue #76 
- [x] Class `ListedLicenseException` is just `LicenseException` in 2.3.  This probably makes sense with the proposed changes for Custom Exceptions
- [x] Classes `NoAssertionLicense`, `NoneLicense`, `NoAssertionText`, and `NoneText` does not exist in SPDX 2.3. Related to issue #76 
- [x] `OrLaterOperator` and `WithExceptionOperator` license property type is `AnyLicenseInfo` in 2.3 - related to other type issues listed above

**Comment by zvr** [comment]
Basic questions on the modeling of licensing info:

- should licensing info be _properties_ of elements or _relationships_ between elements and licenses?
- to which Elements does it apply? `Artifact` or `Software/Package`, `Software/File`, `Software/Snippet`? Or to a new `Software/SoftwareArtifact` class?

**Comment by swinslow** [comment]
Setting to 3.0 since I suspect there are a few details that would be helpful for us to walk through live and confirm on before closing this.

@zvr for the properties vs. relationships question, I think we're tracking that in #254 so we can discuss that one there. For the question about which Elements it applies to, I agree with having them apply to the new `SoftwareArtifact` class so I think we're resolved on that.

**Comment by goneall** [comment]
It looks like the above punch list has been resolved - if any are still open, please open a fresh issue.
