### ISSUE TITLE
TODO's need to be "filled in"

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#367]
Below are the files that currently have a `TODO` for a description:

- [x] ./Core/Classes/LifecycleScopedRelationship.md
- [x] ./Core/Properties/extension.md
- [x] ./Core/Properties/identifierLocator.md
- [x] ./Core/Properties/issuingAuthority.md
- [x] ./Core/Properties/scope.md
- [x] ./Core/Vocabularies/HashAlgorithm.md
- [x] ./Core/Vocabularies/LifecycleScopeType.md
- [x] ./Security/Properties/actionStatementTime.md
- [x] ./Software/Classes/SoftwareDependencyRelationship.md
- [x] ./Software/Properties/conditionality.md
- [x] ./Software/Properties/contentIdentifier.md:
- [x] ./Software/Properties/packageUrl.md
- [x] ./Software/Properties/softwareLinkage.md
- [x] ./Software/Vocabularies/DependencyConditionalityType.md
- [x] ./Software/Vocabularies/SoftwareDependencyLinkType.md
- [x] ./Security/Properties/catalogType.md
- [x] ./Security/Properties/impactStatementTime.md
- [x] ./Security/Properties/statusNotes.md
- [x] ./Security/Properties/vexVersion.md
- [x] ./SimpleLicensing/SimpleLicensing.md

**Comment by puerco** [comment]
I'll take `./Security/Properties/actionStatementTime.md`

**Comment by jeff-schutt** [comment]
I'll take  `./Software/Properties/contentIdentifier.md`

**Comment by goneall** [comment]
Kate's going to take the relationship / dependency TODO:'s.

- https://github.com/spdx/spdx-3-model/issues/462#issuecomment-1714744171

**Comment by goneall** [comment]
@jeff-schutt mentioned on the tech call that if he has bandwidth, he'll take the identity relationships:
-  ./Core/Properties/identifierLocator.md
-  ./Core/Properties/issuingAuthority.md

**Comment by goneall** [comment]
@kestewart will take LifecycleScopedRelationship and HashAlgorithm

**Comment by goneall** [comment]
@goneall will take the SimpleLicensingInfo

**Comment by goneall** [comment]
@puerco - would you mind taking a look at the security related definitions?

**Comment by goneall** [comment]
PR #503 fixes the TODO's for extensions

**Comment by goneall** [comment]
I added PR #590 for issuing authority and PR #589 for simple licensing

**Comment by kestewart** [comment]
Added https://github.com/spdx/spdx-3-model/pull/615 to address /Core/Vocabularies/LifecycleScopeType.md
Added https://github.com/spdx/spdx-3-model/pull/614 to address ./Core/Classes/LifecycleScopedRelationship.md

**Comment by goneall** [comment]
All done :)
