### ISSUE TITLE
Meta Issue: RDF Specific Issues

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#468]
We have a few RDF specific issues to resolve.

This issue summarizes all open issues:

- [ ] https://github.com/spdx/spdx-3-model/issues/461
- [ ] https://github.com/spdx/spdx-3-model/issues/460
- [ ] https://github.com/spdx/spdx-3-model/issues/439
- [ ] https://github.com/spdx/spdx-3-model/issues/438
- [ ] https://github.com/spdx/spdx-3-model/issues/434
- [ ] https://github.com/spdx/spdx-3-model/issues/418

**Comment by goneall** [comment]
@zvr @aamedina @sbarnum - As active RDF contributors, let me know if I missed anything.

Suggest we work on these right after RC2 release.

We can schedule a one of our tech calls for the RDF issues for any of the above not already resolved.

**Comment by henkbirkholz** [comment]
I am especially interested in an answer for the question raised in #439 (SSVC question).
