### ISSUE TITLE
3.0-RC2 punchlist

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-3-model#622]
Following are the remaining issues / PRs / actions needed before the RC2 release:

- [x] Review / merge #588 - decide if we need to resolve how individual ID's are handled before RC2 release
- [x] Resolve verification of packages - involves PR #602, PR #609, PR #610, PR #611, issue #345
- [x] Review / merge #613 
- [x] Review / merge #614 
- [x] Review / merge #615 
- [x] Review / merge #616 
- [x] Review / merge #617 
- [x] Review / merge #618
- [x] Review / merge #619
- [x] Review / merge #620
- [x] Review / merge #621
- [x] Review / merge #623 
- [x] Verify #228 is resolved with the relationship definitions
- [x] Verify #356 is resolved with the relationship definitions
- [x] Security related documentation - identifierLocator, catalogType, impactStatementTime, statusNotes, vexVersion
- [x] Create a PR for #387 or decide if it is not required for 3.0 release
- [x] Verify #527 is resolved with the relationship definitions
- [x] Verify #543 is resolved with the relationship definitions
- [x] Verify #544 is resolved with the relationship definitions
- [x] Verify #545 is resolved with the relationship definitions
- [x] Resolve #570 
- [x] Resolve #584 
- [x] Review and update SPDX-license-expressions.md - https://github.com/spdx/spdx-spec/pull/877
- [x] Review and update RDF-object-model-and-identifier-syntax.md - @sbarnum will follow up on if the manually created model diagram will work.  @zvr - will we have the diagram generation ready for RC2?  The manual update of the diagrams have been added to spdx-spec PR  https://github.com/spdx/spdx-spec/pull/883
- [x] Update Annex F External repository identifiers - These are now identifiers - propose we leave this out of 3.0 - Agreed on tech call 13 Feb 2024 to remove
- [x] remove using-SPDX-lite.md - we'll add it back in after RC2 - https://github.com/spdx/spdx-spec/pull/879
- [x] remove how-to-use.md - we'll add it back in after RC2 - this is already gone
- [x] Review / merge https://github.com/spdx/spdx-spec/pull/878 - removes annexes we agreed to remove for 3.0
- [x] rewrite file-tags.md - This can not be re-written until we decide on Tag/Value - propose postponing adding this until after RC2 - Agreed on tech call 13 Feb 2024 to temporarily remove
- [x] Add in support level #627
- [x] Produce a PDF (or word) version of the spec
- [x] Review / merge spec PR to remove old chapters once we know what the intended structure of the spec repo is - see https://github.com/spdx/spdx-spec/issues/881 - there is now a PR https://github.com/spdx/spdx-spec/pull/883

**Comment by goneall** [comment]
Completed
